chores: added extra checks.

diff --git a/.github/workflows/cmake-build-artifacts.yml b/.github/workflows/cmake-build-artifacts.yml
--- a/.github/workflows/cmake-build-artifacts.yml
+++ b/.github/workflows/cmake-build-artifacts.yml
@@ -101,8 +101,17 @@ jobs:
       run: |
         cd ${{ steps.strings.outputs.binary-output-dir }}
         APP_PATH=$(find . -name "*.app" -type d | head -n 1)
-        macdeployqt "$APP_PATH"
+        echo "App path found: $APP_PATH"
+        macdeployqt -verbose=3 "$APP_PATH"
+
+        if [ ! -d "*.app" ]; then
+          echo "Error: No .app file found!"
+          exit 1
+        fi
+        echo ".app file found successfully."
+
         APP_NAME=$(find . -name "*.app" -type d | head -n 1 | xargs basename)
+        echo "App name found: $APP_NAME"
         zip -r sokketter-ui.zip "${APP_NAME}"
 
     - name: Rename sokketter-cli (Windows-only)
